//autogenerated by "pnpm watch"
export const modelsList = [
  "chest.glb",
  "coal.glb",
  "copper-ingot.glb",
  "crude-mallet.glb",
  "crude-workbench.glb",
  "gem-moon.glb",
  "gem-sun.glb",
  "ice.glb",
  "iron-hammer.glb",
  "iron-ingot.glb",
  "ore-copper.glb",
  "ore-iron.glb",
  "pickaxe-iron.glb",
  "stone-hammer.glb",
  "stone.glb",
  "wood.glb",
];
